version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db-server
    restart: always
    environment:
      MYSQL_DATABASE: 'your_database_name'
      MYSQL_USER: 'your_mysql_user'
      MYSQL_PASSWORD: 'your_mysql_password'
      MYSQL_ROOT_PASSWORD: 'your_mysql_root_password'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
